services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: database
    env_file:
      - enviroment.env
    ports:
      - "5432:5432"

  application:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - enviroment.env
    depends_on:
      - database
    ports:
      - "8080:8080"
